### ISSUE TITLE
点击获取抽卡链接按钮后应用程序崩溃

### ISSUE THREAD

**Issue by ChenNick464800678** [lgou2w/HoYo.Gacha#15]
点击跃迁里的读取链接按钮之后闪退
![image](https://github.com/lgou2w/HoYo.Gacha/assets/21167884/74744efb-92b8-4c79-b268-cbe20784caac)
windows版本如下
![image](https://github.com/lgou2w/HoYo.Gacha/assets/21167884/e35138ff-8fa0-431f-9689-ea93a23121c9)
不知道是什么原因导致的，麻烦作者帮忙看看，谢谢！

**Comment by lgou2w** [comment]
1. 确定是 `点击跃迁里的读取链接按钮之后闪退` 而不是 `运行exe` 就闪退？
2. 能否提供完整的 `崩坏：星穹铁道` 数据缓存目录。见下例子：

> `D:\miHoYo\Star Rail\Game\StarRail_Data\webCaches`

**Comment by ChenNick464800678** [comment]
> 1. 使用快捷键 ⊞ Windows + R 输入 `msinfo32` 回车并截图详细的系统信息。
> 2. 确定是 `点击跃迁里的读取链接按钮之后闪退` 而不是 `运行exe` 就闪退？
> 3. 能否提供完整的 `崩坏：星穹铁道` 数据缓存目录。见下例子：
> 
> > `D:\miHoYo\Star Rail\Game\StarRail_Data\webCaches`
> 
> > > 以及该 `webCaches` 目录下的所有文件的截图。
> 
> 4. 尝试更新您的 `WebView2 Runtime` 版本后再尝试是否会复现此问题：
> 
> > 下载地址：https://developer.microsoft.com/zh-cn/microsoft-edge/webview2/#download-section

1.这是详细的系统信息截图
![image](https://github.com/lgou2w/HoYo.Gacha/assets/21167884/29e632b1-cc4b-4e1a-906c-df9c95e52b5a)
2.是点击跃迁里的读取链接按钮之后闪退的，打开程序不会闪退，我还添加了我的账号
![image](https://github.com/lgou2w/HoYo.Gacha/assets/21167884/2f18e91e-4b05-4cfe-b31d-4a1b67926c0c)
3.完整的数据缓存目录：F:\Program Files\Star Rail\Games\StarRail_Data\webCaches
![image](https://github.com/lgou2w/HoYo.Gacha/assets/21167884/6aeff8ac-3373-4608-a8bb-450568388e18)
4.安装了常青版之后还是闪退

**Comment by lgou2w** [comment]
@ChenNick464800678 

请尝试测试一下这个 debug 构建。下载这个压缩包后把里面的文件解压缩到和你 `HoYo.Gacha.db` 数据库文件相同目录。
运行里面后缀为 .cmd 的文件，尝试复现闪退的问题。最后把后缀为 .log 的日志文件提交一下。

[HoYo_Gacha_0.3.5_debug_build.zip](https://github.com/lgou2w/HoYo.Gacha/files/12909167/HoYo_Gacha_0.3.5_debug_build.zip)

**Comment by ChenNick464800678** [comment]
> @ChenNick464800678
> 
> 请尝试测试一下这个 debug 构建。下载这个压缩包后把里面的文件解压缩到和你 `HoYo.Gacha.db` 数据库文件相同目录。 运行里面后缀为 .cmd 的文件，尝试复现闪退的问题。最后把后缀为 .log 的日志文件提交一下。
> 
> [HoYo_Gacha_0.3.5_debug_build.zip](https://github.com/lgou2w/HoYo.Gacha/files/12909167/HoYo_Gacha_0.3.5_debug_build.zip)
> 
> > 为了避免数据敏感泄露，建议将日志文件通过邮箱发送给我：[`email`](mailto:lgou2w@hotmail.com)

已发送邮件，请查收

**Comment by lgou2w** [comment]
> > @ChenNick464800678
> > 请尝试测试一下这个 debug 构建。下载这个压缩包后把里面的文件解压缩到和你 `HoYo.Gacha.db` 数据库文件相同目录。 运行里面后缀为 .cmd 的文件，尝试复现闪退的问题。最后把后缀为 .log 的日志文件提交一下。
> > [HoYo_Gacha_0.3.5_debug_build.zip](https://github.com/lgou2w/HoYo.Gacha/files/12909167/HoYo_Gacha_0.3.5_debug_build.zip)
> > > 为了避免数据敏感泄露，建议将日志文件通过邮箱发送给我：[`email`](mailto:lgou2w@hotmail.com)
> 
> 已发送邮件，请查收

需要更多信息，请查看邮件正文。

**Comment by lgou2w** [comment]
已在 [0.3.6](https://github.com/lgou2w/HoYo.Gacha/releases/tag/0.3.6) 版本中修复。

**Comment by ChenNick464800678** [comment]
> 已在 [0.3.6](https://github.com/lgou2w/HoYo.Gacha/releases/tag/0.3.6) 版本中修复。

新版可以正常使用了，再次感谢！
