### ISSUE TITLE
UIGF导出版本变更

### ISSUE THREAD

**Issue by BTMuli** [lgou2w/HoYo.Gacha#20]
目前UIGF标准已经更新到3.0，但是应用内代码仍是2.2版本

可能会造成其他应用（如胡桃）导入数据异常

**Comment by lgou2w** [comment]
> UIGF v2.3 `item_id` 变更为必要字段。

按照文档说明版本向下兼容。那么 v3.0 应该是可以导入旧版本的数据。

我审查和测试了 [Snap.Hutao/releases/1.9.8](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.9.8) 是可以正常导入并显示当前应用 v2.2 的 UIGF 数据（包含集录祈愿）。

https://github.com/DGP-Studio/Snap.Hutao/blob/fad5f8a/src/Snap.Hutao/Snap.Hutao/Model/InterChange/GachaLog/UIGF.cs#L56-L69

**Comment by BTMuli** [comment]
> 我审查和测试了 [Snap.Hutao/releases/1.9.8](https://github.com/DGP-Studio/Snap.Hutao/releases/tag/1.9.8) 是可以正常导入并显示当前应用 v2.2 的 UIGF 数据（包含集录祈愿）。

按照标准，2.2并未包含集录祈愿相关字段说明，胡桃确实可以导入2.2版本的数据，但是对于适配集录祈愿的导出而言，其对应的应该是3.0版本的标准

**Comment by lgou2w** [comment]
目前使用 `v2.2` 版本的应用还是偏多数的。
因为 `v2.3` 强制要求 `item_id` 字段并且填写实际的物品内部 ID 值。
这会导致应用的代码破坏性更新，可能还需要请求第三方 API 下载字典。

我个人的观点比较推荐 UIGF 把 `v2.2` 进行 patch 更新以兼容未来的卡池。
