### ISSUE TITLE
想参与项目，有good-first-issue推荐么？

### ISSUE THREAD

**Issue by CanglongCl** [lgou2w/HoYo.Gacha#21]

**Comment by lgou2w** [comment]
目前 `v0.3.x` 版本是没有什么新功能需求或者问题存在的。只负责维护更新确保兼容性。

我建议想研究代码或者参与开发贡献的话可以 Checkout [`v1`](https://github.com/lgou2w/HoYo.Gacha/tree/v1) 分支查看项目结构代码。
（PS：不过因为个人目前比较忙，没有太多时间进行开发重构迭代

**Comment by CanglongCl** [comment]
> 目前 `v0.3.x` 版本是没有什么新功能需求或者问题存在的。只负责维护更新确保兼容性。
> 
> 
> 
> 我建议想研究代码或者参与开发贡献的话可以 Checkout [`v1`](https://github.com/lgou2w/HoYo.Gacha/tree/v1) 分支查看项目结构代码。
> 
> （PS：不过因为个人目前比较忙，没有太多时间进行开发重构迭代

是的，就是想做V1（代码太漂亮了，来学习一下）。所以目前有什么需求么？

**Comment by lgou2w** [comment]
> > 目前 `v0.3.x` 版本是没有什么新功能需求或者问题存在的。只负责维护更新确保兼容性。
> > 我建议想研究代码或者参与开发贡献的话可以 Checkout [`v1`](https://github.com/lgou2w/HoYo.Gacha/tree/v1) 分支查看项目结构代码。
> > （PS：不过因为个人目前比较忙，没有太多时间进行开发重构迭代
> 
> 是的，就是想做V1（代码太漂亮了，来学习一下）。所以目前有什么需求么？

目前 v1 的核心代码（Rust）全部重构完成：数据存储、抽卡链接获取、更新记录等。
前端界面方面的话，如下图所示：基本的组件、布局、账户添加编辑、设置界面相关都已实现。

![账户](https://github.com/lgou2w/HoYo.Gacha/assets/13819168/865f492c-9320-41cf-8155-4ecfc8b29eb0)
![设置](https://github.com/lgou2w/HoYo.Gacha/assets/13819168/160a4b39-ddbe-4824-a150-d06316e9604c)

---

还没有实现的有：主页界面、抽卡记录展示的各个组件（v0.3.x 版本展示图所示）。
之前一直在苦恼是继续使用老版本的界面呢还是重构一个全新的内容 :(
