### ISSUE TITLE
原神的祈愿记录异常

### ISSUE THREAD

**Issue by FujishiroOtone** [lgou2w/HoYo.Gacha#25]
![S}X5MUQKY@53@IW6A(6GGC](https://github.com/lgou2w/HoYo.Gacha/assets/19571014/d35c7789-4380-4b52-970b-5d0ecf01d4a9)
![image](https://github.com/lgou2w/HoYo.Gacha/assets/19571014/6f8795cf-4630-47b1-8ae7-ff6b908db979)
![image](https://github.com/lgou2w/HoYo.Gacha/assets/19571014/0f9fc502-f253-47b0-8167-cc49363f3997)

我有一段记录用的是原神开服比较老的时候的抽卡记录保存工具，还没有统一祈愿记录标准的，我后面自己手动加进去的，id格式不一样，是根据id来识别排序的吗？

**Comment by lgou2w** [comment]
是的（按记录的 `ID` 从小到大排序）。因为用日期时间不能保证该条记录是唯一性的。
由于目前工具是没有记录的修改和编辑功能，所以只能在其他工具或者 `UIGF` 的 JSON 文件编辑后再导入。
