### ISSUE TITLE
啥时候增加一个导出JSON记录的功能

### ISSUE THREAD

**Issue by MuNitCat** [lgou2w/HoYo.Gacha#26]

**Comment by lgou2w** [comment]
目前工具支持 `原神` 和 `崩坏：星穹铁道` 的抽卡记录导入和导出功能。

在添加指定游戏账号后。在 `祈愿` 或 `跃迁` 页面的顶部右上角工具栏可见。如下图所示：

![图片](https://github.com/lgou2w/HoYo.Gacha/assets/13819168/3951de94-3455-4c24-abbd-e7e58e7487dd)

---

由于还没有规范 `绝区零` 的记录格式标准，这个暂时不支持导入和导出。

**Comment by lgou2w** [comment]
如果是需要导出 `绝区零` 的记录。那么请等待社区规范记录格式标准后，工具会第一时间做兼容更新。
如有其他问题或者建议，请重新打开问题，欢迎讨论。
