### ISSUE TITLE
希望能够兼容https://github.com/biuuu/genshin-wish-export这个原神项目的json导出文件或者excel导出表格

### ISSUE THREAD

**Issue by pigg289** [lgou2w/HoYo.Gacha#27]
https://github.com/biuuu/genshin-wish-export
这个原神项目的json文件和导出的表格都无法导入本项目，希望能够添加相关兼容，附件添加了这个原神工具导出的抽卡json。
[gacha-list-100309609.json](https://github.com/user-attachments/files/16139780/gacha-list-100309609.json)

**Comment by lgou2w** [comment]
> https://github.com/biuuu/genshin-wish-export 这个原神项目的json文件和导出的表格都无法导入本项目，希望能够添加相关兼容，附件添加了这个原神工具导出的抽卡json。 [gacha-list-100309609.json](https://github.com/user-attachments/files/16139780/gacha-list-100309609.json)

这个项目是支持导出为 [`UIGF`](https://uigf.org/zh/standards/uigf.html) 标准 JSON 格式文件的。是因为 UIGF 的字典 API 离线导致这个工具导出时报错。
可以在下面 Issues 追踪到：
[issue: #253](https://github.com/biuuu/genshin-wish-export/issues/253)
[issue: #265](https://github.com/biuuu/genshin-wish-export/issues/265)

---

已经帮你自动转换为 UIGF v2.2 版本格式文件：[HoYo.Gacha_原神祈愿记录_UIGF_100309609_20240709_160350.json](https://github.com/user-attachments/files/16140274/HoYo.Gacha_._UIGF_100309609_20240709_160350.json)
下载此文件后在 HoYo.Gacha 工具选择并导入即可。

届时我会写一个网页小工具可以方便在线转换。

**Comment by pigg289** [comment]
转换后的文件成功导入了，谢谢你

**Comment by lgou2w** [comment]
不用客气的 ;)
