### ISSUE TITLE
会触发windows的威胁隔离

### ISSUE THREAD

**Issue by JcXGTcW** [lgou2w/HoYo.Gacha#29]
Trojan:Win32/Bearfoos.A!ml
![image](https://github.com/lgou2w/HoYo.Gacha/assets/59499984/70f3580d-0c5f-45ab-846c-197a09f7364f)

**Comment by lgou2w** [comment]
见：https://github.com/tauri-apps/tauri/issues/2486

~~目前无法修复此问题。请手动添加信任项即可~~

**Comment by lgou2w** [comment]
已在 v1.2.6 版本中修复：https://github.com/lgou2w/HoYo.Gacha/releases/latest
