### ISSUE TITLE
抽数统计错误

### ISSUE THREAD

**Issue by AmazingFrog** [lgou2w/HoYo.Gacha#30]
我用[genshin-wish-export](https://github.com/biuuu/genshin-wish-export)这个仓库的软件导出来的数据如图
![(9N06R`F9`DCZPX29S)(G G](https://github.com/lgou2w/HoYo.Gacha/assets/27079914/04494874-9771-4795-b0f6-39607c058da6)
我自己把上述软件的数据改成uigf 3.0的格式以后导入到hoyo.gacha以后如下
![image](https://github.com/lgou2w/HoYo.Gacha/assets/27079914/497e4ff3-6013-4816-8627-d5447e586278)
可以看到像七七和希格雯的抽数都是错的（我的七七都是77发出的
然后我把我转换过后的数据导入[抽卡分析网站](https://genshin.voderl.cn/)，可以发现数据是对的
![72~CD0VTG35AIQZ7 ND$A_P](https://github.com/lgou2w/HoYo.Gacha/assets/27079914/e5feb48c-fd34-4bff-be52-3398a2aa63a7)
现在的错误就只有在角色up池有问题，武器和常驻是对的

**Comment by lgou2w** [comment]
> 我自己把上述软件的数据改成uigf 3.0的格式以后导入到hoyo.gacha以后如下

请问是否是把 `gacha-list-102362489.json` 这种文件名格式的数据转换后导入的？
如果是。可以提供一份文件数据帮你修正，或等待网页小工具。请见：https://github.com/lgou2w/HoYo.Gacha/issues/27#issuecomment-2216910728

推测是开服时的抽卡记录没有 ID 导入后数据乱序的问题。

**Comment by lgou2w** [comment]
网页小工具在线转换：https://hoyo-gacha.lgou2w.com/static/genshin/gwe2uigf.html

**Comment by AmazingFrog** [comment]
@lgou2w 我用了网页转换以后就对了，可能是我转换的时候id不对吧，我为了省事，直接从0自增了

**Comment by lgou2w** [comment]
;)

如有其他问题或者建议，请重新打开问题，欢迎讨论。
