### ISSUE TITLE
ZZZ的常驻频段读取不全？

### ISSUE THREAD

**Issue by SpecterHi** [lgou2w/HoYo.Gacha#31]
![图片](https://github.com/lgou2w/HoYo.Gacha/assets/2437251/b72e7aff-518c-4133-9ff6-9e50ac392c81)
![图片](https://github.com/lgou2w/HoYo.Gacha/assets/2437251/7c766cc5-dddf-4a0f-9422-42cc16e5050c)
可以看到实际上此时有23*5+3=118抽，但是只统计了最近的80抽。也因此对于出金和四星的统计都连带缺失了。

使用的是0.4.0的Windows版本

**Comment by lgou2w** [comment]
@SpecterHi 
请提供一份调频链接（工具的调频页面顶部输入框复制图标按钮）发送到邮件：mailto:lgou2w@hotmail.com
