### ISSUE TITLE
优化方向的建议

### ISSUE THREAD

**Issue by xxbhpan** [lgou2w/HoYo.Gacha#33]
1、希望增加up角色花费抽数统计
2、希望在统计界面也能看到4星或者A级物品的分析

**Comment by xxbhpan** [comment]
3、希望账号管理界面的头像能够实现自定义，这样就可以挂着我们喜爱的角色了。
4、UIGF现在有3.0版本了，希望能及时跟进一下。
5、希望可以将通过链接获取的祈愿记录导出成excel形式的raw-data数据。

**Comment by lgou2w** [comment]
目前 `v0` 版本只会再更新几个小版本以兼容其他语言确保图标图片正常加载。不会再添加任何新功能。
更多的时间会着重 `v1` 新版本的重构和开发。

您可以在这个 #28 问题追踪里面提出新功能或者建议。

**Comment by xxbhpan** [comment]
ok，相关建议将会挪至 # 28
