### ISSUE TITLE
兄弟跪求绝区零国际服的支持。万分感谢！！

### ISSUE THREAD

**Issue by yecongjia** [lgou2w/HoYo.Gacha#34]
兄弟跪求绝区零国际服的支持。万分感谢！！

**Comment by lgou2w** [comment]
请你能详细描述问题原因吗？是工具无法运行还是数据无法加载

**Comment by cokebar** [comment]
我这里提示：
内部错误：系统找不到指定的路径。 (os error 3)

**Comment by Estrella-071** [comment]
这边绝区零登入的是Asia服，记录能导入到工具正常显示

**Comment by yecongjia** [comment]
> 请你能详细描述问题原因吗？是工具无法运行还是数据无法加载

我这边的情况是用奇游进的国际服，然后打开抽卡页面后，在工具里点击获取连接，提示无法获取。

**Comment by yecongjia** [comment]
> 请你能详细描述问题原因吗？是工具无法运行还是数据无法加载

抱歉是我脑残了，我忘记新建角色了。。。

**Comment by lgou2w** [comment]
> > 请你能详细描述问题原因吗？是工具无法运行还是数据无法加载
> 
> 抱歉是我脑残了，我忘记新建角色了。。。

读取链接是获取当前选中账号 UID 相匹配的链接。并且链接有时效性（一般为一天）。
重新打开抽卡页面是让游戏生成新的链接，然后供工具读取。
