### ISSUE TITLE
新手问题，请问如何将excel文件转为json

### ISSUE THREAD

**Issue by strutest** [lgou2w/HoYo.Gacha#36]
请问如何将excel文件转为json？曾经的抽卡记录中断过，只保留了excel表格，现在想在软件里加载完整的抽卡记录该怎么做，谢谢

**Comment by lgou2w** [comment]
如果是 `原神` 的 Excel 抽卡记录文件。那么按下列步骤进行转换：

1. 将 Excel 文件在 https://genshin-gacha-export.danmu9.com/ 转换为 `GWE` 格式 JSON 文件。
2. 再把第一步的 `gacha-list-xxxxx.json` 文件在 https://hoyo-gacha.lgou2w.com/static/genshin/gwe2uigf.html 转换为 UIGF v2.2 标准 JSON 文件。
3. 打开软件工具选择第二步的文件导入即可。
