### ISSUE TITLE
绝区零调频抽卡详情url读取失败，多次重试无效

### ISSUE THREAD

**Issue by XTR0411** [lgou2w/HoYo.Gacha#37]
![image](https://github.com/user-attachments/assets/e940c2c8-5576-42a3-a261-305d63d76eb8)
![image](https://github.com/user-attachments/assets/12549e14-d1a0-4122-9ea3-1631f3d00b3e)
绝区零调频抽卡详情url读取失败，多次重试无效

**Comment by lgou2w** [comment]
根据图片来看，应该是你游戏的 UID 和工具右上角选中的账号 UID 不匹配导致的。
请尝试在工具切换或添加对应 UID 的账号后重试。

**Comment by XTR0411** [comment]
ZZZ真是什么狗屎 我才发现 好像没有快捷复制uid的功能
