### ISSUE TITLE
在 1080P 系统分辨率下过大的缩放值导致窗口遮挡无法调节大小

### ISSUE THREAD

**Issue by black-zero358** [lgou2w/HoYo.Gacha#40]
![image](https://github.com/user-attachments/assets/60b1056f-41a4-465d-bd60-863dfd895141)

系统：win10
窗口模式下的窗口大小超过了屏幕大小，且无法调节

**Comment by lgou2w** [comment]
工具的窗口强制设定最小为 `1152x864` 的分辨率。

从提供的图片来看这是一张 `1920x1080` 分辨率。为什么高度超过了最小值却不能调节呢？

**Comment by lgou2w** [comment]
临时方案：可以点击最大化窗口按钮解决此问题。
