### ISSUE TITLE
支持绝区零导入导出

### ISSUE THREAD

**Issue by earthjasonlin** [lgou2w/HoYo.Gacha#43]
绝区零和崩铁的api完全是一样的，一点差别没有（B、A、S分别为rank2~4），所以其实可以完全兼容srgf的，就像这个 [zzz-signal-search-export](https://github.com/earthjasonlin/zzz-signal-search-export)

**Comment by lgou2w** [comment]
Wait UIGF v4.0
https://github.com/UIGF-org/UIGF-org.github.io/pulls
