### ISSUE TITLE
星铁跃迁未找到有效的抽卡链接

### ISSUE THREAD

**Issue by BUAAYurika** [lgou2w/HoYo.Gacha#44]
![image](https://github.com/user-attachments/assets/7a35906a-2137-4f8c-8f8e-1e2edcf63b10)
可以看到背景已经打开历史记录界面了，但还是提示找不到

**Comment by lgou2w** [comment]
请检查你的游戏 UID 和工具添加的账号 UID 是否一致。

**Comment by lgou2w** [comment]
如果还有其他问题，请重新打开此问题。
