### ISSUE TITLE
无法导入 UIGF v4.0 的祈愿记录

### ISSUE THREAD

**Issue by MESFET5198** [lgou2w/HoYo.Gacha#45]
![image](https://github.com/user-attachments/assets/620ac7bf-e245-4bd5-b5e0-7c1d5b15a0c7)
不知道是不是Hutao的UIGF版本太新了，而且最新版还取消了UIGF 2和3记录文件的导出

[Snap Hutao UIGF.json](https://github.com/user-attachments/files/16345813/Snap.Hutao.UIGF.json)

**Comment by lgou2w** [comment]
这个记录数据文件的信息头如下：

```json
{
  "info": {
    "uid": "***",
    "lang": "zh-cn",
    "export_time": "2024-07-22 01:15:42",
    "export_timestamp": "1721582142002",
    "export_app": "Genshin Helper",
    "export_app_version": "1.2.4",
    "uigf_version": "v2.2"
  },
  "list": [...]
}
```

可以看到是名为 `Genshin Helper` 的工具导出的。
但是它的 `export_timestamp` 字段是一个 `字符串` 类型。而查阅 UIGF 文档这个字段应当是 `长整型`。
无法导入 Hutao 是因为也是明确要求这个字段是长整型。

解决方法：用文本编辑器（如记事本）打开这个 `138895794-20240722011537.json` 文件，将字段后面值的双引号去掉。
保存后重新导入工具即可。

```diff
-"export_timestamp":"1721582142002",
+"export_timestamp":1721582142002,
```

---

Json Schema:
https://uigf.org/zh/standards/uigf-legacy-v2.3.html#json-schema

Introducing UIGF v2.4:
https://github.com/UIGF-org/UIGF-org.github.io/blob/3c6e22311a1d9b4285eb6c5317db1b77bd4023b2/docs/.vuepress/public/schema/uigf.json#L16-L19

**Comment by MESFET5198** [comment]
> 这个记录数据文件的信息头如下：
> 
> ```json
> {
>   "info": {
>     "uid": "***",
>     "lang": "zh-cn",
>     "export_time": "2024-07-22 01:15:42",
>     "export_timestamp": "1721582142002",
>     "export_app": "Genshin Helper",
>     "export_app_version": "1.2.4",
>     "uigf_version": "v2.2"
>   },
>   "list": [...]
> }
> ```
> 
> 可以看到是名为 `Genshin Helper` 的工具导出的。 但是它的 `export_timestamp` 字段是一个 `字符串` 类型。而查阅 UIGF 文档这个字段应当是 `长整型`。 无法导入 Hutao 是因为也是明确要求这个字段是长整型。
> 
> 解决方法：用文本编辑器（如记事本）打开这个 `138895794-20240722011537.json` 文件，将字段后面值的双引号去掉。 保存后重新导入工具即可。
> 
> ```diff
> -"export_timestamp":"1721582142002",
> +"export_timestamp":1721582142002,
> ```
> 
> Json Schema： https://uigf.org/zh/standards/uigf-legacy-v2.3.html#json-schema
> 
> 介绍 UIGF v2.4： https://github.com/UIGF-org/UIGF-org.github.io/blob/3c6e22311a1d9b4285eb6c5317db1b77bd4023b2/docs/.vuepress/public/schema/uigf.json#L16-L19

不好意思上传错了json文件，但是按照你的方法修改Genshin Helper导出的json成功导入了。但在对照Hutao里面的记录时发现，我在Genshin Helper导出的记录里面少了一部分记录。所以问题还是回到了无法导入Hutao的祈愿记录，按照之前的思路我也去看了以下UIGF的介绍，但是没看到v4.0相关的文档。

**Comment by lgou2w** [comment]
暂不支持 UIGF v4.0 的导入导出。

**Comment by lgou2w** [comment]
@MESFET5198

可以使用网页工具：https://hoyo-gacha.lgou2w.com/static/genshin/uigf40to22.html
将 UIGF v4.0 版本的祈愿记录转换为 UIGF v2.2 来导入到工具中。
