### ISSUE TITLE
無法開啟應用

### ISSUE THREAD

**Issue by Sigma-68** [lgou2w/HoYo.Gacha#49]
不好意思，開啟檔案一直白屏顯示Microsoft Edge 無法讀取及寫入其資料目錄，
應用程式也是完全控制權限，不知道該怎麼解決...
![1721987611171](https://github.com/user-attachments/assets/c0247146-cf3d-420b-9808-4f995060492f)

**Comment by lgou2w** [comment]
1. 请按下 <kbd>Windows</kbd> + <kbd>R</kbd> 快捷键，输入 `%USERPROFILE%\AppData\Local\com.lgou2w.hoyo.gacha` 后回车。

2. 然后 `右键此文件夹` - `属性` - `安全`
3. 依次查看 `组或用户名` 内的用户是否拥有 `完全控制` 权限。

**Comment by Sigma-68** [comment]
阿 原來是資料夾權限，問題解決了，真的是非常感謝!
