### ISSUE TITLE
之前用的snap 胡桃，用的UIGF4.0版本抽卡记录，这个用的2.2无法导入

### ISSUE THREAD

**Issue by lingo76** [lgou2w/HoYo.Gacha#51]

**Comment by lgou2w** [comment]
旧版本 v0 暂不支持 UIGF v4.0 的导入导出。

最近会暂时写一个网页工具方便自动转换的。

**Comment by lgou2w** [comment]
@lingo76 

可以使用网页工具：https://hoyo-gacha.lgou2w.com/static/genshin/uigf40to22.html
将 UIGF v4.0 版本的祈愿记录转换为 UIGF v2.2 来导入到工具中。

**Comment by lingo76** [comment]
有了，非常感谢！！
