### ISSUE TITLE
崩铁导入和快捷方式

### ISSUE THREAD

**Issue by YuMingkun520** [lgou2w/HoYo.Gacha#53]
今天发现了这个宝藏软件，感觉用着很舒服，不用每次都打开powershell命令行了，而且还可以本地缓存，原神我和我的室友们都用的提瓦特小助手，这个可以下载历史记录导入到这个软件里面，但是崩铁，我们用的星穹铁道小助手，这个不可以下载历史记录，请问作者大大是否可以联系作者让他添加一个这个功能，或者你添加你个图像识别模块识别我们在星穹铁道小助手上面的历史记录并合并记录，再或者添加一个手动选项，可以让我手动补齐超过180天的历史记录。求求作者了。

**Comment by YuMingkun520** [comment]
另外，我在创建快捷方式的时候，电脑显示磁盘已满。但是我创建别的应用和文件的快捷方式的时候是没有这个问题的，这是为什么啊。我的电脑是win 11专业版。作者可以帮帮我么。

**Comment by lgou2w** [comment]
> 请问作者大大是否可以联系作者让他添加一个这个功能

这些小程序大部分都是公司性质的闭源代码，我可能没有能力联系请求这些功能。

> 或者你添加你个图像识别模块识别我们在星穹铁道小助手上面的历史记录并合并记录，再或者添加一个手动选项

未来新版本 v1 会有手动编辑记录数据的功能。

> 我在创建快捷方式的时候，电脑显示磁盘已满

无法重现此问题。我个人觉得这应该是你的系统用户文件夹权限问题。您可以尝试把 HoYo.Gacha.exe 移动到其他目录，再右键 - 发送到桌面快捷方式 尝试解决。

**Comment by Housenk** [comment]
您好，请问一下，以下问题（“待导入的 UIGF 或 SRGF 数据文件格式不正确missing field `uid` at line 1 column 124”）出现的原因会是啥导致的？先前有使用过别的软件来分析抽卡记录，然后原神那边导出来的（.json）记录能成功导入，然后崩铁这边这个导入就报错了

**Comment by lgou2w** [comment]
> 您好，请问一下，以下问题（“待导入的 UIGF 或 SRGF 数据文件格式不正确missing field `uid` at line 1 column 124”）出现的原因会是啥导致的？先前有使用过别的软件来分析抽卡记录，然后原神那边导出来的（.json）记录能成功导入，然后崩铁这边这个导入就报错了

@Housenk 
您应该导入的是 UIGF v4.0 版本格式的跃迁记录。
而工具 v0 版本只支持 UIGF v2.2（原神）和 SRGF v1.0（崩坏：星穹铁道）的旧版本格式。

https://github.com/lgou2w/HoYo.Gacha/issues/52#issuecomment-2282570959
可以暂时使用网页工具：https://hoyo-gacha.lgou2w.com/static/starrail/uigf40tosrgf.html
将 UIGF v4.0 版本的跃迁记录转换为 SRGF v1.0 来导入到工具中。
