### ISSUE TITLE
原神重复数据记录问题

### ISSUE THREAD

**Issue by BUAAHM** [lgou2w/HoYo.Gacha#56]
在更新记录时，读取链接和更新祈愿两个按钮快速点击了几下，发现数据出现异常，部分记录出现了重复
期望能优化按钮操作或者数据检查(。・ω・。)
![image](https://github.com/user-attachments/assets/ca8e4045-23dd-423a-9535-52dd8bc6fa22)
![image](https://github.com/user-attachments/assets/e69102f2-8578-4bea-bb3d-5cfc9efb6afe)
（出现了20条重复数据）

**Comment by lgou2w** [comment]
就在几个小时前也是第一次遇到这个情况。同样的也是 `2024-11-20` 这一天的记录，出现 20 条重复。
而且这 20 条数据的特点都是 `id` 字段不同，其他字段完全一模一样。

![图片](https://github.com/user-attachments/assets/2eb8a302-d7d3-488d-b264-ab619518fa2d)

> 读取链接和更新祈愿两个按钮快速点击了几下

我刚刚测试了自己的账号无法复现这个问题。

---

我重新审查了代码，`id` 这个字段是严格使用 miHoYo 官方 Http API 返回的数据，不存在自己生成或者修改的。

**Comment by lgou2w** [comment]
现在比较可能的是因为 `2024-11-20 06:00` 的小米渠道服停止充值和注册，开放账号转服到官方服务器的功能。
然后 `11-20` 的抽卡记录在最近几天，被抽卡服务器自动修正或修改 `id` 字段了。

举个例子：
您的图中记录 `3055` 到 `3074` 是在 `11-20` 这一天用工具获取并保存到数据库的。
然后最近几天您又进行抽卡并重新获取新的记录了，但是正好那 `20` 条记录受到了转服的影响，`id` 字段被修正了。
导致又出现了 `20` 条相同数据，但不同 `id` 的记录。

**Comment by lgou2w** [comment]
目前这个 `id` 字段被官方修正了还只是猜测，不能完全肯定。
但这是遇到的第二例，等待后续其他用户有没有遇到同样是 `11-20` 的记录出现重复的。

**Comment by lgou2w** [comment]
查阅了一些公告，确实在 `2024-11-20` 号 06:00 - 11:00 是版本维护更新。转服申请开放时间是在维护结束后。

并且也追踪到一位同样在当天有抽卡记录的，但是是在 10 点多提前开服然后抽的 20 抽。并没有出现重复的问题。

![图片](https://github.com/user-attachments/assets/50851fdb-cdd1-48fb-a9e0-af1022020762)

---

两例受影响的记录时间分别是 12:05 和 19:12。

**_个人猜测_**：大概率是转服功能出现小问题，导致当天 11-20 号 11:00 维护结束后的抽卡记录被合并账号功能影响出现了丢失或其他问题。后续解决完引发了抽卡记录的 `id` 字段（重新插入？生成新的？）

**Comment by lgou2w** [comment]
这不应该是工具的问题，但还需要更多的例子来证实这个猜测是成立的。

暂时的解决方案：手动编辑数据库把旧的重复记录删除掉。对应您的图中 `3055 - 3074` 条，而高亮选中的是新的记录。

**Comment by Tang0310** [comment]
我的也出现了11月20号重复的情况
![image](https://github.com/user-attachments/assets/915a4e98-d1a3-4d53-b445-cee35fa08620)

**Comment by Tang0310** [comment]
问一下如何手动修改记录

**Comment by lgou2w** [comment]
> 问一下如何手动修改记录

如果现在就需要解决的话，可以把工具同目录的 `HoYo.Gacha.db` 文件发送到我的邮箱：mailto:lgou2w@hotmail.com
修改完成后我会用邮件回复您。
