### ISSUE TITLE
更新跃迁记录时显示全屏的 JSON Object 数据

### ISSUE THREAD

**Issue by FlandiaYingman** [lgou2w/HoYo.Gacha#7]
不太好语言描述：
![image](https://github.com/lgou2w/HoYo.Gacha/assets/9929037/451ebea2-c21e-4591-9c57-6b8b5617e848)

**Comment by upgrade-1** [comment]
可能是网络问题？我把代理关了好像就没了

**Comment by lgou2w** [comment]
因为目前还处于**开发者测试版**，还有很多没有做完的功能。这个更新跃迁的页面代码里面就是这样的。

将于下个快照版进行修改调整设计。感谢反馈！
