### ISSUE TITLE
数据库文件不应该放在工作目录（cwd）

### ISSUE THREAD

**Issue by everything411** [lgou2w/HoYo.Gacha#8]
程序应该在固定的目录下存放数据库文件，例如在程序本体同目录存放。

现在程序的行为是在程序的工作目录下存放和读取数据库文件，如图，当前工作目录是家目录，运行程序时自动在家目录下创建了数据库。
<img width="779" alt="workdirectory" src="https://github.com/lgou2w/HoYo.Gacha/assets/32010059/98055a65-8598-488a-8e1e-eb687f7f68df">

这个问题会导致从开始菜单运行程序时程序报错，因为从开始菜单运行的程序的cwd是C:\Windows\system32，普通用户没有读写权限，会导致程序崩溃。
<img width="259" alt="image" src="https://github.com/lgou2w/HoYo.Gacha/assets/32010059/2cc4e133-25c8-4d0b-ba03-17326111dc50">

一个可能的方案是在程序启动时将程序的cwd调整为程序所在目录。

**Comment by lgou2w** [comment]
目前默认方法 `SQLite` 的 `URI` 使用的是相对路径，所以它是基于 `cwd` 目录的：

https://github.com/lgou2w/HoYo.Gacha/blob/cd4bff09593a4ac976d4625c57b76fadbb166129/src-tauri/src/storage/impl_storage.rs#L66-L69

https://github.com/lgou2w/HoYo.Gacha/blob/cd4bff09593a4ac976d4625c57b76fadbb166129/src-tauri/src/storage/impl_storage.rs#L73

第 `66` 行 `DATABASE = sqlite://HoYo.Gacha.db?mode=rwc` 是相对路径的。
解决方法就是使用 `current_exe() + DATABASE` 就行。

---

BTW：因为目前个人有事情需要处理，项目的更新会滞后一段时间。
您可以暂时使用：创建一个快捷方式去运行应用或许可以解决。
或者也欢迎 PR :smile:

**Comment by lgou2w** [comment]
已在正式版 [0.3.0](https://github.com/lgou2w/HoYo.Gacha/releases/tag/0.3.0) 中修改调整。
